#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomWebServer.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class PostBackHandlerView : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 2 "..\..\Views\PostBackHandlerView.cshtml"

    public dynamic Model { get; set; }

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");


WriteLiteral("\r\n<!DOCTYPE html>\r\n<html lang=\"en\">\r\n  <head>\r\n    <meta charset=\"utf-8\">\r\n    <t" +
"itle>Bootstrap, from Twitter</title>\r\n    <meta name=\"viewport\" content=\"width=d" +
"evice-width, initial-scale=1.0\">\r\n    <meta name=\"description\" content=\"\">\r\n    " +
"<meta name=\"author\" content=\"\">\r\n\r\n    <!-- Le styles -->\r\n    <link href=\"/css/" +
"bootstrap.css\" rel=\"stylesheet\">\r\n    <style type=\"text/css\">\r\n      body {\r\n   " +
"     padding-top: 60px;\r\n        padding-bottom: 40px;\r\n      }\r\n    </style>\r\n " +
"   <link href=\"/css/bootstrap-responsive.css\" rel=\"stylesheet\">\r\n\r\n    <!-- HTML" +
"5 shim, for IE6-8 support of HTML5 elements -->\r\n    <!--[if lt IE 9]>\r\n      <s" +
"cript src=\"/js/html5shiv.js\"></script>\r\n    <![endif]-->\r\n\r\n    <!-- Fav and tou" +
"ch icons -->\r\n    <link rel=\"apple-touch-icon-precomposed\" sizes=\"144x144\" href=" +
"\"/ico/apple-touch-icon-144-precomposed.png\">\r\n    <link rel=\"apple-touch-icon-pr" +
"ecomposed\" sizes=\"114x114\" href=\"/ico/apple-touch-icon-114-precomposed.png\">\r\n  " +
"    <link rel=\"apple-touch-icon-precomposed\" sizes=\"72x72\" href=\"/ico/apple-touc" +
"h-icon-72-precomposed.png\">\r\n                    <link rel=\"apple-touch-icon-pre" +
"composed\" href=\"/ico/apple-touch-icon-57-precomposed.png\">\r\n                    " +
"               <link rel=\"shortcut icon\" href=\"/ico/favicon.png\">\r\n  </head>\r\n\r\n" +
"  <body>\r\n\r\n    <div class=\"navbar navbar-inverse navbar-fixed-top\">\r\n      <div" +
" class=\"navbar-inner\">\r\n        <div class=\"container\">\r\n          <button type=" +
"\"button\" class=\"btn btn-navbar\" data-toggle=\"collapse\" data-target=\".nav-collaps" +
"e\">\r\n            <span class=\"icon-bar\"></span>\r\n            <span class=\"icon-b" +
"ar\"></span>\r\n            <span class=\"icon-bar\"></span>\r\n          </button>\r\n  " +
"        <a class=\"brand\" href=\"#\">Project name</a>\r\n          <div class=\"nav-co" +
"llapse collapse\">\r\n            <ul class=\"nav\">\r\n              <li class=\"active" +
"\"><a href=\"#\">Home</a></li>\r\n              <li><a href=\"#about\">About</a></li>\r\n" +
"              <li><a href=\"#contact\">Contact</a></li>\r\n              <li class=\"" +
"dropdown\">\r\n                <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dro" +
"pdown\">Dropdown <b class=\"caret\"></b></a>\r\n                <ul class=\"dropdown-m" +
"enu\">\r\n                  <li><a href=\"#\">Action</a></li>\r\n                  <li>" +
"<a href=\"#\">Another action</a></li>\r\n                  <li><a href=\"#\">Something" +
" else here</a></li>\r\n                  <li class=\"divider\"></li>\r\n              " +
"    <li class=\"nav-header\">Nav header</li>\r\n                  <li><a href=\"#\">Se" +
"parated link</a></li>\r\n                  <li><a href=\"#\">One more separated link" +
"</a></li>\r\n                </ul>\r\n              </li>\r\n            </ul>\r\n      " +
"      <form class=\"navbar-form pull-right\">\r\n              <input class=\"span2\" " +
"type=\"text\" placeholder=\"Email\">\r\n              <input class=\"span2\" type=\"passw" +
"ord\" placeholder=\"Password\">\r\n              <button type=\"submit\" class=\"btn\">Si" +
"gn in</button>\r\n            </form>\r\n          </div><!--/.nav-collapse -->\r\n   " +
"     </div>\r\n      </div>\r\n    </div>\r\n\r\n    <div class=\"container\">\r\n      \r\n  " +
"    <!-- Example row of columns -->\r\n        <div class=\"row\">\r\n");


            
            #line 80 "..\..\Views\PostBackHandlerView.cshtml"
             if (Model.IsPostBack)
            {

            
            #line default
            #line hidden
WriteLiteral("                <div class=\"span12\">\r\n                    <h1>\r\n                 " +
"       Congratulations, ");


            
            #line 84 "..\..\Views\PostBackHandlerView.cshtml"
                                    Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("!\r\n");


            
            #line 85 "..\..\Views\PostBackHandlerView.cshtml"
                         if(Model.Form.ContainsKey("flavor"))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <small> We have the flavors ");


            
            #line 87 "..\..\Views\PostBackHandlerView.cshtml"
                                                   Write(Model.Form["flavor"]);

            
            #line default
            #line hidden
WriteLiteral(" in stock!</small>\r\n");


            
            #line 88 "..\..\Views\PostBackHandlerView.cshtml"
                        }
                        else
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <small> Not liking icecream is un-American!</small>\r\n" +
"");


            
            #line 92 "..\..\Views\PostBackHandlerView.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </h1>\r\n                </div>\r\n");


            
            #line 95 "..\..\Views\PostBackHandlerView.cshtml"
            }
            else
            {

            
            #line default
            #line hidden
WriteLiteral(@"                <div class=""span12"">
                    <form id=""myPostForm"" action=""/PostbackHandler"" method=""POST"">
                        <fieldset>
                            <legend>My Crappy Postpack Form!</legend>
                            <label>Name</label>
                            <input name=""myName"" type=""text"" placeholder=""Type something"">
                            <span class=""help-block"">Choose your favorite ice cream flavor.</span>
");


            
            #line 105 "..\..\Views\PostBackHandlerView.cshtml"
                             foreach(var flavor in Model.Flavors)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <label class=\"checkbox\">\r\n                       " +
"             <input name=\"flavor\" type=\"checkbox\" value=\"");


            
            #line 108 "..\..\Views\PostBackHandlerView.cshtml"
                                                                           Write(flavor);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 108 "..\..\Views\PostBackHandlerView.cshtml"
                                                                                    Write(flavor);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </label>\r\n");


            
            #line 110 "..\..\Views\PostBackHandlerView.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                            <button type=\"submit\" value=\"submit\" class=\"btn\">Subm" +
"it</button>\r\n                        </fieldset>\r\n                    </form>\r\n " +
"               </div>\r\n");


            
            #line 115 "..\..\Views\PostBackHandlerView.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral(@"        </div>

      <hr>

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src=""http://code.jquery.com/jquery-1.10.1.min.js""></script>
    <script src=""/js/bootstrap.js""></script>

  </body>
</html>");


        }
    }
}
#pragma warning restore 1591
