#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomWebServer.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class PostbackHandlerView : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 2 "..\..\Views\PostbackHandlerView.cshtml"

    public dynamic Model { get; set; }

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");


WriteLiteral("\r\n<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\">\n    <title" +
">Bootstrap, from Twitter</title>\n    <meta name=\"viewport\" content=\"width=device" +
"-width, initial-scale=1.0\">\n    <meta name=\"description\" content=\"\">\n    <meta n" +
"ame=\"author\" content=\"\">\n\n    <!-- Le styles -->\n    <link href=\"/css/bootstrap." +
"css\" rel=\"stylesheet\">\n    <style type=\"text/css\">\n      body {\n        padding-" +
"top: 60px;\n        padding-bottom: 40px;\n      }\n    </style>\n    <link href=\"/c" +
"ss/bootstrap-responsive.css\" rel=\"stylesheet\">\n\n    <!-- HTML5 shim, for IE6-8 s" +
"upport of HTML5 elements -->\n    <!--[if lt IE 9]>\n      <script src=\"/js/html5s" +
"hiv.js\"></script>\n    <![endif]-->\n\n    <!-- Fav and touch icons -->\n    <link r" +
"el=\"apple-touch-icon-precomposed\" sizes=\"144x144\" href=\"/ico/apple-touch-icon-14" +
"4-precomposed.png\">\n    <link rel=\"apple-touch-icon-precomposed\" sizes=\"114x114\"" +
" href=\"/ico/apple-touch-icon-114-precomposed.png\">\n      <link rel=\"apple-touch-" +
"icon-precomposed\" sizes=\"72x72\" href=\"/ico/apple-touch-icon-72-precomposed.png\">" +
"\n                    <link rel=\"apple-touch-icon-precomposed\" href=\"/ico/apple-t" +
"ouch-icon-57-precomposed.png\">\n                                   <link rel=\"sho" +
"rtcut icon\" href=\"/ico/favicon.png\">\n  </head>\n\n  <body>\n\n    <div class=\"navbar" +
" navbar-inverse navbar-fixed-top\">\n      <div class=\"navbar-inner\">\n        <div" +
" class=\"container\">\n          <button type=\"button\" class=\"btn btn-navbar\" data-" +
"toggle=\"collapse\" data-target=\".nav-collapse\">\n            <span class=\"icon-bar" +
"\"></span>\n            <span class=\"icon-bar\"></span>\n            <span class=\"ic" +
"on-bar\"></span>\n          </button>\n          <a class=\"brand\" href=\"#\">Project " +
"name</a>\n          <div class=\"nav-collapse collapse\">\n            <ul class=\"na" +
"v\">\n              <li class=\"active\"><a href=\"#\">Home</a></li>\n              <li" +
"><a href=\"#about\">About</a></li>\n              <li><a href=\"#contact\">Contact</a" +
"></li>\n              <li class=\"dropdown\">\n                <a href=\"#\" class=\"dr" +
"opdown-toggle\" data-toggle=\"dropdown\">Dropdown <b class=\"caret\"></b></a>\n       " +
"         <ul class=\"dropdown-menu\">\n                  <li><a href=\"#\">Action</a>" +
"</li>\n                  <li><a href=\"#\">Another action</a></li>\n                " +
"  <li><a href=\"#\">Something else here</a></li>\n                  <li class=\"divi" +
"der\"></li>\n                  <li class=\"nav-header\">Nav header</li>\n            " +
"      <li><a href=\"#\">Separated link</a></li>\n                  <li><a href=\"#\">" +
"One more separated link</a></li>\n                </ul>\n              </li>\n     " +
"       </ul>\n            <form class=\"navbar-form pull-right\">\n              <in" +
"put class=\"span2\" type=\"text\" placeholder=\"Email\">\n              <input class=\"s" +
"pan2\" type=\"password\" placeholder=\"Password\">\n              <button type=\"submit" +
"\" class=\"btn\">Sign in</button>\n            </form>\n          </div><!--/.nav-col" +
"lapse -->\n        </div>\n      </div>\n    </div>\n\n    <div class=\"container\">\n  " +
"    \n      <!-- Example row of columns -->\n        <div class=\"row\">\r\n");


            
            #line 80 "..\..\Views\PostbackHandlerView.cshtml"
             if (Model.IsPostBack)
            {

            
            #line default
            #line hidden
WriteLiteral("                <div class=\"span12\">\r\n                    <h1>\r\n                 " +
"       Congratulations, ");


            
            #line 84 "..\..\Views\PostbackHandlerView.cshtml"
                                    Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("!\r\n");


            
            #line 85 "..\..\Views\PostbackHandlerView.cshtml"
                         if(Model.Form.ContainsKey("flavor"))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <small> We have the flavors ");


            
            #line 87 "..\..\Views\PostbackHandlerView.cshtml"
                                                   Write(Model.Form["flavor"]);

            
            #line default
            #line hidden
WriteLiteral(" in stock!</small>\r\n");


            
            #line 88 "..\..\Views\PostbackHandlerView.cshtml"
                        }
                        else
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <small> Not liking icecream is un-American!</small>\r\n" +
"");


            
            #line 92 "..\..\Views\PostbackHandlerView.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </h1>\r\n                </div>\r\n");


            
            #line 95 "..\..\Views\PostbackHandlerView.cshtml"
            }
            else
            {

            
            #line default
            #line hidden
WriteLiteral(@"                <div class=""span12"">
                    <form id=""myPostForm"" action=""/PostbackHandler"" method=""POST"">
                        <fieldset>
                            <legend>My Crappy Postpack Form!</legend>
                            <label>Name</label>
                            <input name=""myName"" type=""text"" placeholder=""Type something"">
                            <span class=""help-block"">Choose your favorite ice cream flavor.</span>
");


            
            #line 105 "..\..\Views\PostbackHandlerView.cshtml"
                             foreach(var flavor in Model.Flavors)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <label class=\"checkbox\">\n                        " +
"            <input name=\"flavor\" type=\"checkbox\" value=\"");


            
            #line 108 "..\..\Views\PostbackHandlerView.cshtml"
                                                                           Write(flavor);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 108 "..\..\Views\PostbackHandlerView.cshtml"
                                                                                    Write(flavor);

            
            #line default
            #line hidden
WriteLiteral("\n                                </label>\r\n");


            
            #line 110 "..\..\Views\PostbackHandlerView.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                            <button type=\"submit\" value=\"submit\" class=\"btn\">Subm" +
"it</button>\n                        </fieldset>\n                    </form>\n    " +
"            </div>\r\n");


            
            #line 115 "..\..\Views\PostbackHandlerView.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral(@"        </div>

      <hr>

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src=""http://code.jquery.com/jquery-1.10.1.min.js""></script>
    <script src=""/js/bootstrap.js""></script>

  </body>
</html>");


        }
    }
}
#pragma warning restore 1591
